In [47]:
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm
import time
import requests
import cursor


#адрес с библотеками
base_url='https://www.anapioficeandfire.com/api'

def response(url):
    return requests.get(url, timeout=10)

def soup(url):
    return BeautifulSoup(response.text, 'lxml')

#парсинг книг
books=response(base_url+'/books').json()
books_df=pd.DataFrame(books)
#парсинг домов
houses=response(base_url+'/houses').json()
houses_df=pd.DataFrame(houses)
houses_df.head()
#фильтрация домов с девизами
params={'hasTitles':'true'}
houseswithtitle=requests.get(base_url+'/houses', params=params).json()
houseswithtitle_df=pd.DataFrame(houseswithtitle)
houseswithtitle_df.head()

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/7,House Arryn of the Eyrie,The Vale,A sky-blue falcon soaring against a white moon...,As High as Honor,"[King of Mountain and Vale (formerly), Lord of...","[The Eyrie (summer), Gates of the Moon (winter)]",https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/16,Coming of the Andals,https://www.anapioficeandfire.com/api/characte...,,[],[https://www.anapioficeandfire.com/api/houses/6],[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/houses/8,House Ashford of Ashford,The Reach,"Tenny, a sun in splendour beneath a chevron in...",Our Sun Shines Bright,[Lord of Ashford],[Ashford],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/10,House Baelish of Harrenhal,The Riverlands,"A field of silver mockingbirds, on a green fie...",,"[Lord Paramount of the Trident, Lord of Harren...",[Harrenhal],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/16,299 AC,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/houses/13,House Banefort of Banefort,The Westerlands,"A black hooded man, on a grey field, within a ...",,[Lord of Banefort],[Banefort],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/229,,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/14,House Bar Emmon of Sharp Point,The Crownlands,"Fretty argent and white, a swordfish embowed h...",,[Lord of Sharp Point],[Sharp Point],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/15,,,,[],[],[https://www.anapioficeandfire.com/api/charact...

In [ ]:
import pandas as pd
import psycopg2
import psycopg2.extras

#подключение к бд
conn_str="host='hh-pgsql-public.ebi.ac.uk' dbname='pfmegrnargs' user='reader' password='NWDMCE5xdipIjRrp'"
conn=psycopg2.connect("host='hh-pgsql-public.ebi.ac.uk' dbname='pfmegrnargs' user='reader' password='NWDMCE5xdipIjRrp'")
query='select * from rnc_Database limit 10'
query2='select display_name, num_sequences, num_organisms, url from rnc_Database limit 10'

cursor=conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
cursor.execute(query)
rnc_db=pd.DataFrame(cursor.fetchall())

cursor.execute(query2)

for row in cursor.fetchall():
    print(row)


cursor.close()
conn.close()

['NONCODE', 234669, 7, 'http://www.noncode.org/']
['VEGA', 0, 0, 'http://vega.sanger.ac.uk/']
['GENCODE', 47677, 2, 'http://gencodegenes.org/']
['ENA', 12086180, 814855, 'https://www.ebi.ac.uk/ena/browser/']
['TAIR', 4406, 1, 'http://www.arabidopsis.org/']
['RefSeq', 120355, 22524, 'http://www.ncbi.nlm.nih.gov/refseq/']
['GeneCards', 425357, 1, 'https://www.genecards.org/']
['RDP', 4779, 2487, 'http://rdp.cme.msu.edu/']
['LNCipedia', 126876, 1, 'http://www.lncipedia.org/']
['WormBase', 25550, 1, 'http://www.wormbase.org/']

In [46]:
rnc_db.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,21,2017-05-02,RNACEN,NONCODE,146,NONCODE,Y,,NONCODE,,1130.0,201.0,244296.0,234669,7,is an integrated knowledge database dedicated ...,http://www.noncode.org/,"[{'upi': 'URS000019B796', 'taxid': 9606}, {'up...",[{'title': 'NONCODE 2016: an informative and v...
1,5,2017-05-17,RNACEN,VEGA,98,VEGA,N,,VEGA,PRJEB4568,NaN,NaN,NaN,0,0,is a repository for high-quality gene models p...,http://vega.sanger.ac.uk/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'The GENCODE v7 catalog of human lo...
2,26,2017-05-01,RNACEN,GENCODE,450,GENCODE,N,,GENCODE,,889.0,32.0,205012.0,47677,2,produces high quality reference gene annotatio...,http://gencodegenes.org/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'GENCODE: the reference human genom...
3,1,2017-05-01,RNACEN,ENA,968,ENA,Y,,ENA,,412.0,10.0,900074.0,12086180,814855,provides a comprehensive record of the world's...,https://www.ebi.ac.uk/ena/browser/,"[{'upi': 'URS00002D0E0C', 'taxid': 10090}, {'u...",[{'title': 'The European Nucleotide Archive in...
4,14,2017-05-01,RNACEN,TAIR,982,TAIR,Y,,TAIR,PRJ_TAIR,384.0,19.0,6227.0,4406,1,is a database of genetic and molecular biology...,http://www.arabidopsis.org/,"[{'upi': 'URS0000591E4F', 'taxid': 3702}, {'up...",[{'title': 'The Arabidopsis Information Resour...